CREATE TABLE oradb.sqlstats
(
    dbuniquename String,
    hostname String,
    snapTime DateTime,
    sql_id FixedString(13),
    plan_hash_value UInt64,
    version_count UInt32,
    sharable_mem Int64,
    persistent_mem Int64,
    runtime_mem Int64,
    sorts Int64,
    loaded_versions Int32,
    open_versions Int32,
    users_opening Int32,
    users_executing Int32,
    fetches Int64,
    executions Int64,
    px_servers_executions UInt64,
    end_of_fetch_count Int64,
    loads Int32,
    first_load_time DateTime,
    last_load_time DateTime,
    last_active_time DateTime,
    invalidations UInt64,
    parse_calls Int64,
    disk_reads Int64,
    direct_writes Int64,
    buffer_gets Int64,
    cpu_time Int64,
    elapsed_time Int64,
    application_wait_time Int64,
    concurrency_wait_time Int64,
    cluster_wait_time Int64,
    user_io_wait_time Int64,
    plsql_exec_time Int64,
    java_exec_time Int64,
    rows_processed Int64,
    command_type UInt16,
    optimizer_cost String,
    parsing_schema_name String,
    kept_versions Int32,
    object_status String,
    sql_profile String,
    program_id UInt32,
    program_line UInt32,
    io_cell_offload_eligible_mb Int64,
    io_interconnect_mb Int64,
    physical_read_requests Int64,
    physical_read_bytes Int64,
    physical_write_requests Int64,
    physical_write_mb Int64,
    optimized_phy_read_requests Int64,
    io_cell_uncompressed_mb Int64,
    io_cell_offload_returned_mb Int64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(snapTime)
ORDER BY (dbuniquename, snapTime)
SETTINGS index_granularity = 8192;
CREATE TABLE oradb.sqlstats_buffer AS oradb.sqlstats ENGINE = Buffer('oradb', 'sqlstats', 16, 14400, 86400, 100000, 1000000, 100000000, 1000000000);
